"""empty message

Revision ID: 4d429c2b34fa
Revises: 
Create Date: 2023-10-02 17:43:36.205711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d429c2b34fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departament',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_departament', sa.String(length=100), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_departament')
    )
    op.create_table('federative_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_state')
    )
    op.create_table('telephone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone_number', sa.String(length=10), nullable=False),
    sa.Column('telephone_house', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telephone_house'),
    sa.UniqueConstraint('telephone_number')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_place', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('federative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['federative_unit_id'], ['federative_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('neighborhood'),
    sa.UniqueConstraint('public_place')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('departament_id', sa.Integer(), nullable=True),
    sa.Column('telephone_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['departament_id'], ['departament.id'], ),
    sa.ForeignKeyConstraint(['telephone_id'], ['telephone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    op.drop_table('address')
    op.drop_table('telephone')
    op.drop_table('federative_unit')
    op.drop_table('departament')
    # ### end Alembic commands ###
